version: '2'
services:
  db:
    image: mongo
    command: "--smallfiles --logpath=/dev/null"
    volumes:
      - .data:/data/db
  web:
    build: .
    command: npm start
    volumes:
      - .:/srv/express-mongo
      - /srv/express-mongo/node_modules
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      PORT: 3000
